swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/{accountID}/transactions:
    get:
      tags:
        - Accounts and Transactions Module
      summary: Account transactions
      description: API for retrieving transactions from an account for the current month
      security:
        - Bearer: []
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountID
          description: ID of an account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: List of transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Unauthorized User
        '403':
          description: Forbidden, no access rights
        "404":
          description: Account not found
        "500":
          description: Internal Server Error

  /transactions/{transactionID}:
    get:
      tags:
        - Accounts and Transactions Module
      summary: View details of a transaction
      description: API for retrieving a specific transaction
      security:
        - Bearer: []
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Unauthorized User
        '403':
          description: Forbidden, no access rights
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      tags:
        - Accounts and Transactions Module
      summary: Update transaction's category and/or note
      description: API for updating transaction's category and/or note
      security:
        - Bearer: []
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: body
          name: updates
          description: Updated transaction's category and note
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthorized User
        '403':
          description: Forbidden, no access rights
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
    type: object
    properties:
      transactionID:
        type: string
        description: transaction ID
      date:
        type: string
        format: date-time
        description: date of transaction
      description:
        type: string
        description: description of transaction
      amount:
        type: number
        description: amount of transaction
      balance:
        type: number
        format: double
        description: available balance
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: transaction note
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: transaction's category
      note:
        type: string
        description: transaction's note
